CREATE TABLE "DOCUMENT" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "LANGUAGE" TEXT NOT NULL,
    "FILENAME" TEXT NOT NULL
);
CREATE TABLE "TERM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "LANGUAGE" TEXT NOT NULL,
    "POS" TEXT NOT NULL,
    "STRING" TEXT NOT NULL
);
CREATE TABLE "SURFACE_FORM" (
    "TERM_CODE" INTEGER NOT NULL REFERENCES TERM(ID),
    "FORM" TEXT NOT NULL,
    "FREQUENCY" INTEGER NOT NULL	
);
CREATE TABLE "TERM_IN_DOCUMENT" (
    "TERM_CODE" INTEGER NOT NULL REFERENCES TERM(ID),
    "DOCUMENT_CODE" INTEGER NOT NULL REFERENCES DOCUMENT(ID),
    "START_TOKEN" INTEGER NOT NULL,
    "END_TOKEN" INTEGER NOT NULL,
    PRIMARY KEY (TERM_CODE, DOCUMENT_CODE, START_TOKEN, END_TOKEN)
);
CREATE TABLE "DOMAIN" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "NAME" TEXT NOT NULL
);
CREATE TABLE "DOCUMENT_IN_DOMAIN" (
    "DOCUMENT_CODE" INTEGER NOT NULL REFERENCES DOCUMENT(ID),
    "DOMAIN_CODE" INTEGER NOT NULL REFERENCES DOMAIN(ID),
    "RELEVANCE" REAL NOT NULL,
    PRIMARY KEY (DOCUMENT_CODE, DOMAIN_CODE)
);
CREATE TABLE "TERM_IN_DOMAIN" (
    "TERM_CODE" INTEGER NOT NULL REFERENCES TERM(ID),
    "DOMAIN_CODE" INTEGER NOT NULL REFERENCES DOMAIN(ID),
    "FREQUENCY" INTEGER NOT NULL,
    "DOCSFREQUENCY" INTEGER NOT NULL,
    "RELEVANCE" REAL NOT NULL,
    PRIMARY KEY (TERM_CODE, DOMAIN_CODE)
);
CREATE TABLE "SENTENCE" (
    -- Store each document's sentences to do sentence alignment.
    -- Sort by ID to get values in document order.
    -- This is a slightly denormalised design for simplicity and (maybe) speed.
    -- PARAGRAPH_NUMBER is not a key, just the index in the document.
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "DOCUMENT_CODE" INTEGER NOT NULL REFERENCES DOCUMENT(ID),
    "PARAGRAPH_NUMBER" INTEGER NOT NULL,
    "TEXT" TEXT NOT NULL
);
CREATE TABLE "DOCUMENT_ALIGNMENT" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "DOC_A" INTEGER NOT NULL REFERENCES DOCUMENT(ID),
    "DOC_B" INTEGER NOT NULL REFERENCES DOCUMENT(ID)
);
CREATE TABLE "TERM_ALIGNMENT" (
    "DOCUMENT_ALIGNMENT_CODE" INTEGER NOT NULL REFERENCES DOCUMENT_ALIGNMENT(ID),
    "TERM_A_CODE" INTEGER NOT NULL REFERENCES TERM(ID),
    "TERM_B_CODE" INTEGER NOT NULL REFERENCES TERM(ID),
    "FREQUENCY" INTEGER NOT NULL,
    PRIMARY KEY (DOCUMENT_ALIGNMENT_CODE, TERM_A_CODE, TERM_B_CODE)
);
CREATE INDEX termindex on "TERM" ("STRING", "POS");
CREATE INDEX domainindex on "DOMAIN" ("NAME");
;
